create project page fixes
SELab-2/UGent-5 pull request #157
Opened 2024-04-29 11:11 UTC by DRIESASTER

requested fixes finished

2024-05-02 15:18 UTC, DRIESASTER commented
nog nie mergen, komt nog wa

2024-05-02 15:22 UTC, DRIESASTER commented
nieuwe alembic op db nodig (enkel op mijn db aangepast)

2024-05-03 10:57 UTC, miboelae requested changes

2024-05-03 10:57 UTC, miboelae commented on frontend/src/views/CreateProjectView.vue
BackgroundContainer zou nog moeten verwijderd worden

2024-05-03 10:57 UTC, miboelae commented on frontend/src/views/CreateProjectView.vue
geval assistenten/lesgevers leeg moet nog uitgewerkt worden, nu is het gewoon een leeg vakje met geen extra uitleg of ze er zijn of niet

2024-05-05 09:27 UTC, DRIESASTER commented on frontend/src/views/CreateProjectView.vue
cv

2024-05-05 15:37 UTC, miboelae requested changes
i18n vergeten

2024-05-08 19:02 UTC, miboelae approved these changes

2024-05-09 13:29 UTC, xerbalind requested changes
- `publish_date` doet nog altijd niets, er wordt nog naar  `is_visible` ipv `publish_date` 
-  wanneer het project aangemaakt is moet er geredirect worden naar de view. nu gebeurd er niets.
- nog i18n ontbreekt voor sommige tekst

2024-05-09 13:29 UTC, xerbalind commented on frontend/src/views/CreateProjectView.vue
> +    console.log(`Deadline changed from ${oldValue.toISOString()} to ${newValue.toISOString()}`);
Enige reden voor al die console.log? mag van mij allemaal weg

2024-05-09 13:29 UTC, xerbalind commented on backend/alembic/versions/1c4eb2b9d8da_.py
> +    pass
Er zijn 7 alembic versions (allemaal) die niets doen -> mogen allemaal weg. Dus eig is er geen verandering in databank.

2024-05-09 13:29 UTC, xerbalind commented on frontend/src/views/CreateProjectView.vue
> +                <span v-else>No assistants found.</span>
hierboven staat al `no instructors found` wat is het verschil?

2024-05-09 13:29 UTC, xerbalind commented on frontend/src/queries/Project.ts
> +            alert("Could not upload files. Please try again.");
miss een vuetify alert ipv een alert box?

2024-05-09 13:29 UTC, xerbalind commented on frontend/src/views/CreateProjectView.vue
> +        console.error("Error during project or group creation or file upload:", error);
hier ook een vuetify alert ipv in console

2024-05-09 13:34 UTC, xerbalind commented
+ Nog een dev mergen

2024-05-10 18:26 UTC, DRIESASTER commented
> * met dev mergen op de branch

gdn

2024-05-12 09:43 UTC, DRIESASTER commented on frontend/src/views/CreateProjectView.vue
> +    console.log(`Deadline changed from ${oldValue.toISOString()} to ${newValue.toISOString()}`);
ja nee idd nie echt reden voor ma da deed ff funky en vergeten weghalen uit debug

2024-05-12 19:52 UTC, closed without merging