Projectpage
SELab-2/UGent-5 pull request #165
Opened 2024-05-02 12:26 UTC by miboelae

2024-05-04 19:39 UTC, pieterjanin requested changes

2024-05-04 19:39 UTC, pieterjanin commented on frontend/src/views/ProjectView.vue
> +                            {{ $t("project.return_course") }}
Ik zou hier gewoon de naam van het vak gebruiken op de knop, niet *terug* naar het vak. Je kan op verschillende manieren op deze pagina terecht komen.

2024-05-04 19:39 UTC, pieterjanin commented on frontend/src/views/ProjectView.vue
> +                    </router-link>
Ik zou dit nog in een aparte component steken.

2024-05-06 13:23 UTC, reyniersbram approved these changes

2024-05-06 13:28 UTC, pieterjanin approved these changes

2024-05-06 15:38 UTC, merged