Subjects
SELab-2/UGent-5 pull request #169
Opened 2024-05-03 12:03 UTC by mattiscauwel

### Vakken overzicht
- Vak bij juiste academiejaar 
- Academiejaren niet hardcoded in script 
- Academie jaar knoppen toggle functionaliteit 
- Klikken naast vak disablen 
- 2e kolom sorteren van vakken 

### Vak overzicht
- Terugknop naar vakken 
- Cards langer maken 
- Knop project aanmaken voor teacher 
- Knop generate inschrijvings link 
- Pr request feedback uitvoeren

2024-05-06 12:20 UTC, reyniersbram commented on frontend/src/views/subject/SubjectsView.vue
> +const selectedAcademicYear = ref<number>(getCurrentAcademicYear());
```suggestion
const selectedAcademicYear = ref<number>(useAcademicYear());
```

2024-05-07 08:43 UTC, mattiscauwel commented on frontend/src/components/subject/header/SubjectHeaderCard.vue
Nee klopt, hou ik me deze week mee bezig

2024-05-07 08:45 UTC, mattiscauwel commented on frontend/src/components/subject/body/projects/list/SubjectProjectsList.vue
Klopt, goed gezien. Is inderdaad overbodig geworden na latere veranderingen en vergeten.

2024-05-15 20:25 UTC, reyniersbram commented on frontend/src/components/subject/body/projects/SubjectProjectPage.vue
De HTML tekst van de beschrijving is hier nog plain tekst, dit zou nog gerenderd moeten worden zoals op de projectpagina

2024-05-16 11:23 UTC, masinnae approved these changes
- if statements bij buttons in orde
- paar stijlpuntjes bv als titel van project te lang is gaat de pijl eronder staan maar die zal ik in de style pr wel aanpakken
- groupen moeten nog toegevoegd worden maar dit gebeurt misschein beter in een nieuwe PR

2024-05-16 11:39 UTC, mattiscauwel commented on frontend/src/components/subject/body/projects/SubjectProjectPage.vue
yes was plan voor volgende pull request zodat ze niet meer te groot worden. Maar best nu ook al?

2024-05-17 12:56 UTC, mattiscauwel commented
Wat er nu ook nieuw is bijgekomen is de opties om te filteren op instructor- en studentenvakken. Deze knoppen staan er gewoon maar doen nog niets. Ook zal er nu met een icoontje zichtbaar zijn of iets een instructor/student vak is, deze icoontjes zijn voorlopig ook nog compleet willekeurig maar zullen geïmplementeerd zijn bij volgende pr.

2024-05-17 14:11 UTC, mattiscauwel commented
er is nog een wijziging geweest met uuid bij de vue queries da ik over het hoofd gezien heb en nog moet oplossen

2024-05-17 23:32 UTC, mattiscauwel commented
### De Grote Subjects PR

Sinds de laatste keer dat deze branch gereviewed is is er bijgekomen:

1.  De merge conflicten door de grote **Queries refactor PR** zijn opgelost
2. De permissions van alle actie knoppen zijn nu gerespecteerd (zoals projecten/vakken aanmaken, register link delen, ...)
3. De vakken overzicht pagina bevat nu filterknoppen die tevoorschijn komen als je zowel instructor als student bent, met deze knoppen kun je de student- en instructor vakken filteren
4. Elk vak wordt nu geïdentificeerd door een icoontje, ofwel ben je student ofwel instructor
5. Er is html rendering toegepast bij de projectopgaves
6. De ronde hoeken van alle cards zijn verwijderd

2024-05-18 10:29 UTC, masinnae approved these changes
ziet er nice uit!

2024-05-18 11:47 UTC, mattiscauwel commented
Kleine fix voor de edit vak knop permissions

2024-05-18 13:12 UTC, reyniersbram requested changes
Ziet er over het algemeen wel goed uit

2024-05-18 13:12 UTC, reyniersbram commented on frontend/src/i18n/locales/nl.ts
> +                "Kopieer de registreer link voor dit vak, deze kan gedeeld worden met studenten om zich te registreren voor het vak.",
```suggestion
            title: "Registratie link",
            snackbar: "Registratie link gekopieerd naar klembord.",
            tooltip:
                "Kopieer de registratie link voor dit vak, deze kan gedeeld worden met studenten om zich te registreren voor het vak.",
```

2024-05-18 13:12 UTC, reyniersbram commented on frontend/src/components/subject/subjectview/header/SubjectHeaderCard.vue
> +                <router-link to="" class="link">
@DRIESASTER niet vergeten dat deze link nog ingevuld zal moeten worden om naar de correcte pagina te gaan

2024-05-18 13:12 UTC, reyniersbram commented on frontend/src/queries/Subject.ts
> +function SUBJECT_UUID_QUERY_KEY(subjectId: string): (string | number)[] {
```suggestion
function SUBJECT_UUID_QUERY_KEY(subjectId: number): (string | number)[] {
```

2024-05-18 13:23 UTC, masinnae commented on frontend/src/components/subject/subjectsview/SubjectsHeaderCard.vue
> +                                {{ academicYear - 1 + "-" + academicYear }}
Ja, ik ga hier wel akkoord mee als, als dat niet te veel moeite is om te wisselen

2024-05-18 13:24 UTC, mattiscauwel commented on frontend/src/views/subject/SubjectView.vue
> +                        v-if="isAdmin || isTeacher"
In de endpoint permissions stond da een assistent geen permissions had om een uuid op te vragen, vandaar dus.

2024-05-18 13:27 UTC, reyniersbram commented on frontend/src/views/subject/SubjectView.vue
> +                        v-if="isAdmin || isTeacher"
Ok, dan kan een assistent het niet :+1:

2024-05-18 13:28 UTC, pieterjanin commented on frontend/src/components/subject/subjectsview/SubjectsHeaderCard.vue
> +                                {{ academicYear - 1 + "-" + academicYear }}
ik ging er van uit dat `23` op `2023-2024` sloeg, dus ook mee eens.

2024-05-18 20:19 UTC, reyniersbram approved these changes

2024-05-18 22:09 UTC, merged