Alembic README + vertaling main readme
SELab-2/UGent-5 pull request #170
Opened 2024-05-04 13:36 UTC by pieterjanin

- Zodat de hele code repository in het Engels zou zijn heb ik de README in de root ook vertaald.
- Alembic README (closes #116 )

2024-05-04 17:20 UTC, miboelae requested changes

2024-05-04 17:20 UTC, miboelae commented on README.md
readme naar de backend bevat een typo in de link

2024-05-04 17:30 UTC, pieterjanin commented on README.md
fixed

2024-05-04 17:31 UTC, miboelae approved these changes

2024-05-06 10:15 UTC, masinnae approved these changes

2024-05-06 10:18 UTC, merged