Projectpage testen + layout
SELab-2/UGent-5 pull request #188
Opened 2024-05-10 18:12 UTC by masinnae

- theme toegepast

- testen geschreven voor volgende views:
NeedHelpButton.vue
ProjectInfo.vue
ProjectSideBar.vue
SubmitInfo.vue
ProjectView.vue

- namen van testen gecorrigeerd

2024-05-11 08:16 UTC, reyniersbram commented
Op de project pagina, bij de knoppen om terug te keren naar een vak, als de naam van het vak te lang is, gaat de tekst uit de knop. Wanneer het scherm breder gemaakt wordt, zijn de knoppen niet meer even groot.

![2024-05-11](https://github.com/SELab-2/UGent-5/assets/55666730/076ec2d3-0185-44e6-ae05-c6c63c2c2c1a)
![2024-05-11_001](https://github.com/SELab-2/UGent-5/assets/55666730/7cb5924a-744a-44c8-8b54-2c557634845b)

2024-05-11 08:22 UTC, reyniersbram requested changes
De

2024-05-11 08:22 UTC, reyniersbram commented on frontend/src/components/project/ProjectSideBar.vue
De knop om naar je groep te gaan heeft als titel het id van de groep in de databank, niet de naam.

2024-05-12 16:50 UTC, masinnae commented
- knop zegt nu "Naar vak" ipv vaknaam
- hierdoor kunnen buttons allemaal dezelfde grootte hebben
- kolommen aangepast afhankelijk van windowgroottte om knoppen op scherm te houden

2024-05-13 09:15 UTC, reyniersbram approved these changes

2024-05-13 12:20 UTC, merged