Submission list voor een vak leerkracht of assistent
SELab-2/UGent-5 pull request #190
Opened 2024-05-11 10:43 UTC by xerbalind

Als je assistent of teacher bent voor een vak is er nu een knop op de project pagina die  alle laatste indieningen  van elke groep oplijst.

2024-05-11 10:45 UTC, xerbalind commented
Closes #151

2024-05-13 09:12 UTC, reyniersbram approved these changes

2024-05-13 09:12 UTC, reyniersbram commented on backend/src/submission/service.py
> +        models.Submission.date == subquery.c.max_date) & (models.Submission.project_id == project_id))
epic query :100:

2024-05-13 15:33 UTC, pieterjanin requested changes

2024-05-13 15:33 UTC, pieterjanin commented on frontend/src/components/project/ProjectInfo.vue
> +            </v-btn>
```suggestion

            <v-card-actions>
                <v-btn v-if="isTeacher" :to="`/project/${project.id}/submissions`" class="...">
                    {{ $t("project.submissions_list_teacher") }}
                </v-btn>
            </v-card-actions>
```
- `v-card-actions` voor de padding
- styling met css

2024-05-13 15:33 UTC, pieterjanin commented on frontend/src/services/project.ts
> +}
idem, zal beschikbaar zijn in `getProjectGroups`

2024-05-13 15:33 UTC, pieterjanin commented on frontend/src/queries/Project.ts
> +        enabled: computed(() => projectId.value !== undefined),
```suggestion
        enabled: !!toValue(projectId),
```
volgens de nieuwe stijl

2024-05-13 15:33 UTC, pieterjanin commented on frontend/src/queries/Project.ts
> +}
misschien nog wachten met mergen totdat Bram's query refactor is doorgevoerd, dan kan je hier `useProjectGroupsQuery` gebruiken.

2024-05-13 15:33 UTC, pieterjanin commented on frontend/src/services/project.ts
> +}
Om consequent te zijn met de rest van de query refactor zou ik deze dan in `services/submission.ts` steken en `getProjectSubmissions` noemen.

2024-05-16 16:30 UTC, xerbalind commented
Er is nu een knop toegevoegd bij een indiening die all bestanden als een zip download

2024-05-17 09:41 UTC, reyniersbram requested changes

2024-05-17 09:41 UTC, reyniersbram commented on frontend/src/components/submission/SubmissionCard.vue
> +    deadline: string;
deadline zou als een Date binnen moeten komen, niet als een string

2024-05-17 09:41 UTC, reyniersbram commented on frontend/src/queries/Project.ts
> +        enabled: computed(() => projectId.value !== undefined),
```suggestion
        enabled: () => !!toValue(projectId),
```
Dit zou de juiste aanpassing zijn

2024-05-17 11:55 UTC, miboelae approved these changes
qua views ok, eventueel i18n van submissionstatus nog in orde brengen, backend kan ik niet testen door docker issues

2024-05-18 13:57 UTC, pieterjanin approved these changes

2024-05-18 18:13 UTC, merged