404 not found + register to subject view: sytling + frontend tests
SELab-2/UGent-5 pull request #213
Opened 2024-05-16 17:29 UTC by masinnae

styling en testen voor:
- NotFoundView.vue
- SubjectRegisterView.vue

2024-05-17 09:25 UTC, reyniersbram requested changes
Mega nice 404 logo

2024-05-17 14:44 UTC, masinnae commented on frontend/src/views/SubjectRegisterView.vue
ik zal hier een issue voor aanmaken.
Lijkt mij persoonlijk niet iets dat in orde gebracht moet worden in de styling PR.

2024-05-17 19:57 UTC, reyniersbram approved these changes

2024-05-18 13:08 UTC, pieterjanin requested changes

2024-05-18 13:08 UTC, pieterjanin commented on frontend/src/i18n/locales/en.ts
> +        cancel: "Cancel",
```suggestion
        register: "You have been invited to join",
        ok: "Accept",
        cancel: "Cancel",
```
Iets in deze zin, ik vind de originele verwoording een beetje barebones.

In het algemeen ook duidelijker als de knop zegt wat hij doet.

2024-05-18 13:08 UTC, pieterjanin commented on frontend/src/i18n/locales/nl.ts
> +        cancel: "Annuleer",
```suggestion
        register: "Je bent uitgenodigd voor",
        ok: "Accepteer",
        cancel: "Annuleer",
```
Idem, mag ook iets gelijkaardigs zijn.

2024-05-18 17:18 UTC, masinnae commented
"registreer" aangepast naar "inschrijven" en de knoppen zeggen nu duidelijk ja en nee

2024-05-18 22:52 UTC, pieterjanin approved these changes

2024-05-19 07:30 UTC, merged