Subjectspage testen
SELab-2/UGent-5 pull request #226
Opened 2024-05-19 21:42 UTC by masinnae

- styling van subjecst en projects pagina om die wat in dezelfde stijl te hebben
- SubjectsView en SubjectView uit die map gehaald om structuur minder complex te maken

testen van volgende views:
- SubjectsView.vue
- SubjectCard.vue
- SubjectsHeaderCard.vue
- SubjectsHeaderContainer.vue
- SubjectIcon.vue

2024-05-21 20:36 UTC, masinnae commented
normaalgezien is op elke pagina:
- white en darktheme correct
- styling gebeurt
- backbuttons waar nodig
- indien meerdere buttons aan zijkant zijn deze even groot gemaakt

moet nog gebeuren:
- query van group bij subject pagina (staat uitgecomment, query moet gewoon nog gefixt worden)

2024-05-21 22:11 UTC, reyniersbram requested changes
ziet er over het algemeen mooi uit, nog een aantal kleinigheidjes

2024-05-21 22:11 UTC, reyniersbram commented on frontend/src/views/subject/CreateSubjectView.vue
>                      </CreateSubjectBody>
De aparte kaartjes hierin mogen misschien iets minder hoog zijn

2024-05-21 22:11 UTC, reyniersbram commented on frontend/src/views/GroupsView.vue
> +                <BackButton
Wanneer het scherm kleiner wordt, komt de tekst buiten beeld te staan
![2024-05-22](https://github.com/SELab-2/UGent-5/assets/55666730/b0c29403-14a2-4f0c-bf37-5862f452a65f)

2024-05-21 22:13 UTC, reyniersbram commented
> moet nog gebeuren:
> 
>     * query van group bij subject pagina (staat uitgecomment, query moet gewoon nog gefixt worden)

Wat is precies het probleem met de query?

2024-05-21 22:16 UTC, masinnae commented
> > moet nog gebeuren:
> > ```
> > * query van group bij subject pagina (staat uitgecomment, query moet gewoon nog gefixt worden)
> > ```
> 
> Wat is precies het probleem met de query?

Hij blijft infinte requests maken en blijft doet de site wat crashen

2024-05-22 10:52 UTC, masinnae commented on backend/README.md
> +alembic upgrade header
strange, heb gewoon van dev gepulled maar daar staat het wel nog juist. ik pas het aan

2024-05-22 13:30 UTC, DRIESASTER commented
inconsistency met de banner stoort mij nog een beetje 
![image](https://github.com/SELab-2/UGent-5/assets/18557795/b8316670-3d31-4e8b-9e9c-3c4efd45796c)
![image](https://github.com/SELab-2/UGent-5/assets/18557795/becfe15a-f19e-485a-9605-d41fd08fac5b)
spacing zou zelfde moeten zijn

2024-05-22 13:31 UTC, DRIESASTER commented
![image](https://github.com/SELab-2/UGent-5/assets/18557795/f47959a7-16f0-4f41-93de-fe1794497dfe)
dit vind ik gwn zowa te groot int algemeen? alsof ik op mijn oma haar iphone iets moet lezen

2024-05-22 13:33 UTC, DRIESASTER commented
![image](https://github.com/SELab-2/UGent-5/assets/18557795/6c479e20-7462-4ff3-a47d-245f330c3bd8)
die checkboxes zijn zowa arbitrair geplaatst precies? nie echt alligned me de rest

2024-05-22 13:33 UTC, DRIESASTER commented
ik ben echt aan het nitpicken trouwens he allemaal al echt goe

2024-05-22 13:53 UTC, DRIESASTER approved these changes
toppie

2024-05-22 19:37 UTC, merged